/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CryptoPriceTrackerRouteImport } from './routes/crypto-price-tracker'
import { Route as FcRouteImport } from './routes/fc'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as PrivacyRouteImport } from './routes/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoPriceTrackerRoute = CryptoPriceTrackerRouteImport.update({
  id: '/crypto-price-tracker',
  path: '/crypto-price-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const FcRoute = FcRouteImport.update({
  id: '/fc',
  path: '/fc',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crypto-price-tracker': typeof CryptoPriceTrackerRoute
  '/fc': typeof FcRoute
  '/marketing': typeof MarketingRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crypto-price-tracker': typeof CryptoPriceTrackerRoute
  '/fc': typeof FcRoute
  '/marketing': typeof MarketingRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crypto-price-tracker': typeof CryptoPriceTrackerRoute
  '/fc': typeof FcRoute
  '/marketing': typeof MarketingRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crypto-price-tracker' | '/fc' | '/marketing' | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crypto-price-tracker' | '/fc' | '/marketing' | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/crypto-price-tracker'
    | '/fc'
    | '/marketing'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CryptoPriceTrackerRoute: typeof CryptoPriceTrackerRoute
  FcRoute: typeof FcRoute
  MarketingRoute: typeof MarketingRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-price-tracker': {
      id: '/crypto-price-tracker'
      path: '/crypto-price-tracker'
      fullPath: '/crypto-price-tracker'
      preLoaderRoute: typeof CryptoPriceTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fc': {
      id: '/fc'
      path: '/fc'
      fullPath: '/fc'
      preLoaderRoute: typeof FcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CryptoPriceTrackerRoute: CryptoPriceTrackerRoute,
  FcRoute: FcRoute,
  MarketingRoute: MarketingRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
